apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: musaele1/nodeapp:latest  # Replace with your DockerHub image
        ports:
        - containerPort: 8080  # Assuming your application listens on port 8080
